NAME = Result

SRC = Animal.cpp Dog.cpp Cat.cpp WrongAnimal.cpp WrongCat.cpp Brain.cpp main.cpp
FLAGS = -Wall -Werror -Wextra
CC = c++

all : $(NAME)

$(NAME) :
			$(CC) $(FLAGS) $(SRC) -o $(NAME)

clean : 
		rm -f $(NAME)