NAME = Result

SRC = Bureaucrat.cpp PresidentialPardonForm.cpp RobotomyRequestForm.cpp ShrubberyCreationForm.cpp Form.cpp Intern.cpp main.cpp
FLAGS = -Wall -Werror -Wextra
CC = c++

all : $(NAME)

$(NAME) :
			$(CC) $(FLAGS) $(SRC) -o $(NAME)

clean : 
		rm -f $(NAME)